### ISSUE TITLE
 declarar el problema.

### ISSUE THREAD

**Issue by angelicabenitezgonzalez** [lorenavargas157/equipo3_gaa_ppi2020#5]
El problema de los individuos, es el desconocimiento turístico y cultural en guatapé. Los aplicativos o plataformas ya existentes relacionadas con el turismo, no presenta una información clara o completa. La consecuencia de esto equivale al poco aprovechamiento de los lugares hermosos de este municipio.

**Comment by juanperezu** [comment]
Declarar el problema de acuerdo a lo visto en la guía 
El problema (u oportunidad) de​ ​“A”  
Es causado por ​“B”  
Tiene el efecto de ​“C”

**Comment by juanperezu** [comment]
Mejorar la redacción
"el problema del aplicativo look up guatape, vendría siendo " Esto te puede sobrar

**Comment by marthaduque** [comment]
Se debe corregir esta parte: El problema de nuestro aplicativo web es el desconocimiento turístico y cultural,
